### ISSUE TITLE
What is the command for this addon ? not /classcolors

### ISSUE THREAD

**Issue by ULTGff** [muhmiauwauWOW/ColorToolsClassColors#1]
Hey, what is the command to access the addon?
I'm playing WoW Classic, and I can't find the command, it's not /classcolors, I've tried lots of other things, but I can't find it. 
Can anyone guide me? 
Thank you for this addon, you just need to specify in the readme the command to use please 
(I'm not very smart, of course, but it won't be just me in this case!)

**Comment by ULTGff** [comment]
I tried:
/ctcc
/ccc
/colortoolsclasscolors
/colortools
/classcolors
/colors

Maybe a problem with WoW Classic ?

**Comment by muhmiauwau** [comment]
Hi, I’m sorry for your odyssey through  all those commands, but in fact there is no command. You can access the options by opening the blizzard options (ESC -> Options) and select the addons tab. There should be an entry called „ ColorTools Class Color“.
