### ISSUE TITLE
[Cata] settings hack no longer needed for 4.4.1

### ISSUE THREAD

**Issue by Road-block** [muhmiauwauWOW/ColorToolsClassColors#2]
```lua
			-- why? 
			--[[if select(4, GetBuildInfo()) < 110000 and select(4, GetBuildInfo()) > 40000 then
				setting = Settings.RegisterAddOnSetting(category, className, ID, ColorToolsClassColorsDB, ColorToolsClassColorsDB[ID], "table", className, defaultValue[ID])
			end]]
```
is no longer needed after Cataclysm Classic patched to 4.4.1 and in fact causes a duplicate registration error for every class.

_Snippet posted is me commenting it out in my local copy but that's the bit needs removing_

**Comment by Road-block** [comment]
Fixed in latest version

**Comment by muhmiauwau** [comment]
Thank you for the hint, i really missed the cata update.
